# Generated by Django 4.2.5 on 2023-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='name',
            field=models.CharField(default='name', max_length=20, verbose_name='Name: '),
        ),
    ]
