# Generated by Django 4.2.5 on 2023-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_propertyphoto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
