# Generated by Django 4.2.5 on 2023-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_property_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.URLField(default='https://i.ytimg.com/vi/n8vcZVHjXeQ/maxresdefault.jpg', verbose_name='URL: '),
        ),
        migrations.DeleteModel(
            name='PropertyPhoto',
        ),
    ]
