# Generated by Django 4.2.5 on 2023-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_property_photos_property_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='isBuy',
            field=models.BooleanField(default=True, verbose_name='Buy: '),
        ),
        migrations.AddField(
            model_name='property',
            name='isRent',
            field=models.BooleanField(default=True, verbose_name='Rent: '),
        ),
    ]
